### ISSUE TITLE
no way to create custom error messages

### ISSUE THREAD

**Issue by Hunter-Houts** [micke/valid_email2#125]
There is no way to create a custom error message to use if a user has an invalid email. This would be a really helpful option. 

`validates :email, 'valid_email_2/email': { mx: true, disposable: true, message: "is not a valid email" }`

"message:" doesn't seem to work.

**Comment by micke** [comment]
I just added a test [here]() that shows you that it is, indeed working.
I do however recommend that you instead utilize rails' validation error translation feature, which imho is the proper way of having your custom error message, it should work something like this:
`config/locales/en.yml`
```yml
en:
  activerecord:
    errors:
      models:
        user:
          attributes:
            email:
              invalid: "is not a valid email address"
```
